use_frameworks! :linkage => :static

platform :ios, '11.0'

target 'DirTree_Example' do
  pod 'DirTree', :path => '../'

  target 'DirTree_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
